---
- name: Deploy Smart Garden Planner
  hosts: localhost
  gather_facts: false

  vars:
    image: "smartgardenacr.azurecr.io/smart-garden:latest"
    container_name: "smart-garden-app"
    resource_group: "smart-garden-rg"
    acr_name: "smartgardenacr"

  tasks:
    - name: Get ACR username
      command: az acr credential show --name smartgardenacr --query "username" -o tsv
      register: acr_username

    - name: Get ACR password
      command: az acr credential show --name smartgardenacr --query "passwords[0].value" -o tsv
      register: acr_password

    - name: Delete existing container
      command: >
        az container delete
        --name {{ container_name }}
        --resource-group {{ resource_group }}
        --yes
      ignore_errors: true

    - name: Deploy new container
      command: >
        az container create
        --resource-group {{ resource_group }}
        --name {{ container_name }}
        --image {{ image }}
        --registry-login-server smartgardenacr.azurecr.io
        --registry-username {{ acr_username.stdout }}
        --registry-password {{ acr_password.stdout }}
        --dns-name-label smart-garden-app
        --ports 8000
        --environment-variables
          GROQ_API_KEY="{{ lookup('env', 'GROQ_API_KEY') }}"
          MONGO_URL="{{ lookup('env', 'MONGO_URL') }}"
        --os-type Linux
        --cpu 1
        --memory 2
        --location centralindia

    - name: Show app URL
      debug:
        msg: "App is live at http://smart-garden-app.centralindia.azurecontainer.io:8000"
